In [1]:
print("HELLO")

HELLO


In [4]:
mhttp://localhost:8888/notebooks/MyfirstNotebook.ipynb#Subtitley_name = "Rob"
print(my_name)

Rob


# Title
## Subtitle

In [1]:
import numpy as np
a = np.array([1,2,3])
print(a)

[1 2 3]


In [3]:
b = np.array([[9,8,7],[6,5,4]])
print(b)

[[9 8 7]
 [6 5 4]]


In [4]:
## Get dimension
a.ndim


1

In [5]:
a.dtype

dtype('int64')

In [7]:
# Get Size
a.itemsize

8

In [9]:
b.itemsize

8

In [11]:
a.size

3

In [13]:
a.nbytes

24

In [15]:
b.itemsize

8

In [17]:
b.nbytes

48

In [ ]:
# Specify your data type 