<center>
    <img src="https://www.clearlyrated.com/brand-logo/talent-path" width="500" alt="cognitiveclass.ai logo"  />
</center>

<h1 style="color:DarkBlue; text-align:center">Data Preprocessing for Linear Regression </h1>

<h2 style="color:DarkOrange;" id="custom-id"> Libraries Included</h2>
<ol style="color:DarkBlue;">
    <li>Pandas as pd</li>
    <li>Numpy as np</li>
    <li>Matplotlib.pyplot as plt</li>
    <li>Sklearn (multiple classes)</li>
</ol>
<i> Please make Make sure that you are looking at the Library List before each lesson starts<i>

<h1> Importing the Libraries </h1>

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

<h1>Importing the Dataset</h1>

In [29]:
dataset = pd.read_csv('Data.csv')
X = dataset.iloc[:,:-1].values #This will grab all the rows and all of the columns except for the last column
y = dataset.iloc[:,-1].values #Specifically targeting the last columns and all of its rows
dataset

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [6]:
# Our dependent variable its our item in the far back in the dataset our matrix of features are in the front
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [7]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


<h1>Scikit-Learn and SimpleImputer</h1>

<center>
    <img src="https://scikit-learn.org/stable/_static/scikit-learn-logo-small.png"/>
</center>
<body>
<h3>What is SKlearn?</h3>
<ol>
    <li>"Simple and efficient tools for predictive data analysis"</li>
    <li>"Accessible to everybody, and reusable in various contexts"</li>
    <li>"Built on NumPy, SciPY, and matplotlib"</li>
    <li>"Opensource, commericially usable - BSD license"</li>
</ol>
</body>

In [15]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values = np.nan, strategy='mean') # Handle nan values and have the stragey as mean
imputer.fit(X[:,1:3]) # Don't include everything, get all rows and 1:3 columns
X[:,1:3] = imputer.transform(X[:,1:3])
print(X)
# France doesn't mean anything to a ML model, we do with binary flags with dummy variables.

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


<h3>SimpleImputer: Allowable Parameters</h3>
<p><i><strong>class sklearn.impute.SimpleImputer(*, missing_values=nan, strategy='mean, fill_value=None, verbose= 0, copy=True, add_indicator=False)</p></i></strong>
    <ol>
    <li><b>Missing values:</b>
        <ol>
            <li>The placeholder for the missing values. All occurrences of missing_values will be imputed. For pandas’ dataframes with nullable integer dtypes with missing values, missing_values should be set to np.nan, since pd.NA will be converted to np.nan.</li>
            </ol>
    <li><b>Strategy: The imputation Strategy</b>
        <ol>
            <li>If “mean”, then replace missing values using the mean along each column. Can only be used with numeric data.?</li> 
            <li>If “median”, then replace missing values using the median along each column. Can only be used with numeric data.</li>
            <li>If “most_frequent”, then replace missing using the most frequent value along each column. Can be used with strings or numeric data. If there is more than one such value, only the smallest is returned.</li>
            <li>If “constant”, then replace missing values with fill_value. Can be used with strings or numeric data.</li>
            <li><i><small>New in version 0.20: strategy=”constant” for fixed value imputation.</li></i></small>
        </ol>
    
    
    
<i><small>source:https://scikit-learn.org/stable/modules/generated/sklearn.impute.SimpleImputer.html?highlight=simpleimputer<i><small>

<h1>OneHotEncoder</h1>
<p>Making independant categorical variables readable<p>

In [19]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(),[0])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

print(X)

[[0.0 1.0 0.0 0.0 44.0 72000.0]
 [1.0 0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 1.0 38.0 61000.0]
 [1.0 0.0 1.0 0.0 40.0 63777.77777777778]
 [0.0 1.0 0.0 0.0 35.0 58000.0]
 [1.0 0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 0.0 48.0 79000.0]
 [1.0 0.0 1.0 0.0 50.0 83000.0]
 [0.0 1.0 0.0 0.0 37.0 67000.0]]


<h3>OneHotEncoder: Allowable Parameters</h3>
<p><i><strong>sklearn.preprocessing.OneHotEncoder(*, categories='auto', drop=None, sparse=True, dtype=<class 'numpy.float64'>, handle_unknown='error')<p><i></strong>
<i><small>In this instance we are not using anything besides its automatic settings.<small>
    <ol>
        <li>In order to look at all the allowable parameters please refer to the link below</li>
    </ol>
    

source:https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.OneHotEncoder.html?highlight=onehotencoder#sklearn.preprocessing.OneHotEncoder</i>

<h1>LabelEncoder</h1>
<p>Encoding the Dependant Variable</p>

In [21]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

print(y)

[0 1 0 0 1 1 0 1 0 1]


In [24]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.2, random_state = 2)
print(y)

[0 1 0 0 1 1 0 1 0 1]


<h1>StandardScaler</h1>
    <p>A simple walk through for feature scaling</p>

In [28]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:,3:] = sc.fit_transform(X_train[:,3:])
X_test[:,3:] = sc.fit_transform(X_test[:,3:])
print(X_train)
print('===============')
print(X_test)

[[0.0 1.0 0.0 -0.5773502691896258 -0.8066752374797971 -0.7213204519277457]
 [0.0 1.0 0.0 -0.5773502691896258 0.6176450728387547 0.5817100418772143]
 [0.0 1.0 0.0 -0.5773502691896258 1.250676321869222 1.2332252887796944]
 [1.0 0.0 1.0 -0.5773502691896258 -1.5979642987678815 -1.093614878729163]
 [1.0 0.0 0.0 1.7320508075688774 -0.3319018007069464 -0.4420996318266829]
 [1.0 0.0 0.0 1.7320508075688774 -0.20881239117324427 -1.2797620921298716]
 [0.0 1.0 0.0 -0.5773502691896258 -0.49015961296456323
  0.11634200837544295]
 [1.0 0.0 1.0 -0.5773502691896258 1.5671919463844557 1.6055197155811116]]
[[1.0 0.0 1.0 -1.0 1.0 1.0]
 [1.0 0.0 0.0 1.0 -1.0 -1.0]]


<small><p><i>sklearn.preprocessing.StandardScaler(*, copy=True, with_mean=True, with_std=True)</i></p></small>

<small><i>Source:https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.StandardScaler.html?highlight=standardscaler#sklearn.preprocessing.StandardScaler</i></small> 